### ISSUE TITLE
Move/add some of the reading preferences test to Base.

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/Preferences.jl#22]
It looks like the preference reading part that is defined in Base is completely untested there. That makes it easy to introduce a mistake that won't be caught until someone runs the Preferences test on master. It would be good if (just like code loading) there were dedicated tests for reading preferences in Base to avoid regressions.

**Comment by staticfloat** [comment]
This was done in https://github.com/JuliaLang/julia/commit/cd81054bae301ccf3a0fe7e0d8f60f167f1203a0
