### ISSUE TITLE
Not working in Pkg.test(...) on julia master

### ISSUE THREAD

**Issue by thofma** [JuliaPackaging/Preferences.jl#31]
Some tests started failing for us. It seems that Preferences.jl stopped working when invoked using `]test`? My module is

```julia
module PTest

using Preferences

function f(flag::Bool)
  @set_preferences!("test" => flag)
  f = @load_preference("test", default = nothing)
  @assert !isnothing(f)
  f
end

end # module PTest
```

The `runtests.jl` file:
```julia
using Test, PTest

PTest.f(true)
```

Then doing `]test PTest` yields
```
ERROR: LoadError: AssertionError: !(isnothing(f))
Stacktrace:
 [1] f(flag::Bool)
   @ PTest ~/PTest/src/PTest.jl:8
 [2] top-level scope
   @ ~/PTest/test/runtests.jl:3
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ none:6
in expression starting at /Users/bla/PTest/test/runtests.jl:3
ERROR: Package PTest errored during testing
```

Note that it works on julia 1.6, 1.7 and also when just run in the REPL.

```
julia> versioninfo()
Julia Version 1.9.0-DEV.122
Commit b4ea0f7c4b* (2022-03-03 08:32 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.6.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

**Comment by fingolfin** [comment]
I've bisected this in the Julia repository, which lead to [this commit](https://github.com/JuliaLang/julia/commit/a7e6038789a1038bb4d8e1f6ed17d266bd22c677) which simply bumps Pkg.jl to a newer version. Luckily that bump only contained two commits, one of which only changes a warning message. The other commit is  https://github.com/JuliaLang/Pkg.jl/commit/e7f1659abd7ae93ce2fbaab491873624cd24eb01 by @staticfloat and @vchuravy and is titled "Improve handling of preferences for sandboxes used in Pkg". So it is very likely that this is the cause of the regression.

**Comment by staticfloat** [comment]
Can you try out https://github.com/JuliaPackaging/Preferences.jl/pull/32 and see if it fixes things for you?  The root issue should be that we were ignoring `Base.preferences_names` inside of `set_preferences!()`, and so since `Pkg.jl` was copying preferences over as `JuliaLocalPreferences.toml`, when you called `set_preferences!()` you created a new file that was immediately shadowed.

**Comment by thofma** [comment]
Yes, this fixes it, thanks!

**Comment by fingolfin** [comment]
@staticfloat could you please make a new release of this package so we can benefit from the fix? Thanks!

**Comment by fingolfin** [comment]
(or anyone else who works on this package)
