### ISSUE TITLE
Target of `set_preferences` unclear

### ISSUE THREAD

**Issue by vchuravy** [JuliaPackaging/Preferences.jl#36]
In https://github.com/JuliaParallel/MPI.jl/issues/570 we noticed that the target of `set_preferences` is not the current active project,
but the project that contains the package in it's Project.toml.

The text in 
https://github.com/JuliaPackaging/Preferences.jl/blob/80b550904ae5b5615ec4168a2135f87c397a92b8/src/Preferences.jl#L188-L191

is a bit confusing since it seemingly implies that `=> nothing` will set at a lower level (e.g. the current Project) a clear project, but instead it is also targeting the Project higher up in the LOAD_PATH.

Should we just always target the current Project?

cc: @staticfloat

**Comment by staticfloat** [comment]
Fixed by #37
