### ISSUE TITLE
Support semicolon, i.e. `@load_preference(key; default = nothing)`?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaPackaging/Preferences.jl#5]
This:
```julia
@load_preference(key; default = nothing)
```

Gives the following error:
```
ERROR: LoadError: LoadError: syntax: invalid syntax ; default = nothing
```

In contrast, this works just fine: 
```julia
@load_preference(key, default = nothing)
```

Would it be possible to support the version of the syntax with the semicolon (i.e. `@load_preference(key; default = nothing)`? It would be consistent with one of the main ways of using keyword arguments in functions.

**Comment by DilumAluthge** [comment]
Bump @staticfloat

**Comment by staticfloat** [comment]
Hmmm, can macros do that?

**Comment by DilumAluthge** [comment]
```
ERROR: syntax: macros cannot accept keyword arguments
```

Hmmm, apparently not.

It's weird, because the syntax  `@load_preference(key, default = nothing)` doesn't seem like a positional argument. But it is.
