### ISSUE TITLE
Why the compat set to Julia 1.0 if it's only functional on 1.6 and above? 

### ISSUE THREAD

**Issue by digital-carver** [JuliaPackaging/Preferences.jl#54]
> Note that the package can be installed on Julia v1.0+ but is only functional on Julia v1.6+.

What is the rationale behind this?

**Comment by StefanKarpinski** [comment]
Presumably so that you can support older Julia versions, but without the ability to set preferences.

**Comment by carstenbauer** [comment]
Can this be closed?
